In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
def activation_function(function_name):
    try:
        if (function_name.lower() == 'sigmoid'):
            return lambda x: 1 / (1 + np.exp(-x))
        elif (function_name.lower() == 'tanh'):
            return lambda x: np.tanh(x)
        elif (function_name.lower() == 'relu'):
            return lambda x: np.maximum(0, x)   
        elif (function_name.lower() == 'leaky_relu'):
            return lambda x: np.where(x > 0, x, 0.01 * x)
        elif (function_name.lower() == 'softmax'):
            return lambda x: np.exp(x) / np.sum(np.exp(x), axis=0)
    except Exception as e:
        print(f"Error finding activation function: {e}")
        return None
        
def activation_derivative(function_name):
    try:
        if (function_name.lower() == 'sigmoid'):
            return lambda x: x * (1 - x)
        elif (function_name.lower() == 'tanh'):
            return lambda x: 1 - np.tanh(x) ** 2
        elif (function_name.lower() == 'relu'):
            return lambda x: np.where(x > 0, 1, 0)
        elif (function_name.lower() == 'leaky_relu'):
            return lambda x: np.where(x > 0, 1, 0.01)
        elif (function_name.lower() == 'softmax'):
            return lambda x: x * (1 - x)
    except Exception as e:
        print(f"Error finding activation derivative function: {e}")
        return None
        
        
def loss_function(function_name):
    try:
        if (function_name.lower() == 'mean_squared_error'):
            return lambda y_true, y_pred: np.mean((y_true - y_pred) ** 2)
        elif (function_name.lower() == 'binary_crossentropy'):
            return lambda y_true, y_pred: -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
        elif (function_name.lower() == 'categorical_crossentropy'):
            return lambda y_true, y_pred: -np.sum(y_true * np.log(y_pred), axis=1).mean()
        elif (function_name.lower() == 'crossentropy'):
            return lambda y_true, y_pred: -np.sum(y_true * np.log(y_pred), axis=1).mean()
    except Exception as e:
        print(f"Error finding loss function: {e}")
        return None

def loss_derivative(function_name):
    try:
        if (function_name.lower() == 'mean_squared_error'):
            return lambda y_true, y_pred: 2 * (y_pred - y_true) / y_true.size
        elif (function_name.lower() == 'binary_crossentropy'):
            return lambda y_true, y_pred: -(y_true / y_pred) + ((1 - y_true) / (1 - y_pred))
        elif (function_name.lower() == 'categorical_crossentropy'):
            return lambda y_true, y_pred: -y_true / y_pred
        elif (function_name.lower() == 'crossentropy'):
            return lambda y_true, y_pred: -y_true / y_pred
    except Exception as e:
        print(f"Error finding loss derivative function: {e}")
        return None

In [ ]:
class Layer:
    def __init__(self, input_size, output_size, function_name='sigmoid'):
        self.W = np.random.randn(output_size, input_size) * 0.01
        self.B = np.zeros((output_size, 1))
        self.function_name = function_name
        print("Weights:")
        print(self.W)
        print("Biases:")
        print(self.B)
            
    def feed_forward(self, X):
        self.Z = np.dot(self.W, X) + self.B
        self.A = activation_function(self.function_name)(self.Z)
        return self.A
    
    def back_propagation(self, dA, X):
        m = X.shape[1]
        dL = dA * activation_derivative(self.function_name)(self.A)
        self.dW = np.dot(dL, X.T) / m
        self.dB = np.sum(dL, axis=1, keepdims=True) / m
        dX = np.dot(self.W.T, dL)
        
        return dX

In [49]:
Layer1 = Layer(3,2)
input_data = np.array([[1], [4], [7]])
true_output = np.array([[0], [1]])


print()
print("Input Data:")
print(input_data)
print()
print("Required Output")
print(true_output)
print()
print("Forward Output")
L1 = Layer1.feed_forward(input_data)
loss_value = loss_function('mean_squared_error')(true_output, L1)
dA = loss_derivative('mean_squared_error')(true_output, L1)

print(L1)
print()
print("Loss Value")
print(loss_value)
print()
print("Back Output")
print(Layer1.back_propagation(dA, input_data))
print()


Layer1.W -= Layer1.dW
Layer1.B -= Layer1.dB
print("Forward Output")
L1 = Layer1.feed_forward(input_data)
loss_value = loss_function('mean_squared_error')(true_output, L1)
dA = loss_derivative('mean_squared_error')(true_output, L1)

print(L1)

print()
print("Loss Value")
print(loss_value)
print()
print("Back Output")
print(Layer1.back_propagation(dA, input_data))
print()


Weights:
[[-0.00108408  0.01426067 -0.00424903]
 [ 0.00087429  0.01141518 -0.00560026]]
Biases:
[[0.]
 [0.]]

Input Data:
[[1]
 [4]
 [7]]

Required Output
[[0]
 [1]]

Forward Output
[[0.50655348]
 [0.50183329]]

Loss Value
0.25238324606444357

Back Output
[[-0.00024615]
 [ 0.00038399]
 [ 0.00015946]]

Forward Output
[[2.12342486e-04]
 [9.99764017e-01]]

Loss Value
5.0388733531324895e-08

Back Output
[[-1.27391563e-08]
 [-5.05591129e-08]
 [-8.83710214e-08]]

